### ISSUE TITLE
SPM: PhantomKit dependecies could not be resolved 

### ISSUE THREAD

**Issue by chnbz** [pawello2222/PhantomKit#7]
Hi,

I am getting an error when I want to add PhantomKit via SPM that the package dependencies couldn't be resolved. Am I doing something wrong or is the package broken? Xcode 13.4 on M1 Macbook

**Comment by pawello2222** [comment]
Hi @chnbz 

You're right - latest Xcode updates seemed to break v0.2.0 - although `main` and `dev` still work (that's why I didn't notice it myself). I haven't created a new version in a while, so I'll bump the version next week (need to do a little bit of cleanup first).

Thanks for raising this. 🙌

**Comment by pawello2222** [comment]
Hi @chnbz 

Version 0.3.0 has just been released - please let me know if you see any issues.

**Comment by chnbz** [comment]
Works like a charm now, thank you so much 🙏🏻
